#开发环境服务器配置
server:
  port: 80
  servlet:
    context-path: /

#设置开启热部署
spring:
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java #需重启的目录
  freemarker:
    cache: false #页面不加载缓存，修改即时生效
  profiles:
    active: dev #环境切换，application(dev/test/prod)